---
- name: mc config directory
  file:
    path: "{{ ansible_user_dir }}/.mc"
    state: directory
    mode: 0755
- name: configure midnight commander
  copy:
    src: "{{ role_path }}/files/mc.ini"
    dest: "{{ ansible_user_dir }}/.mc/ini"
    force: yes
