---
- name: screenrc
  copy:
    src: "{{ role_path }}/files/screenrc"
    dest: "{{ ansible_user_dir }}/.screenrc"
    force: yes
- name: ssh-rc-script
  copy:
    src: "{{ role_path }}/files/ssh.rc.sh"
    dest: "{{ ansible_user_dir }}/.ssh/rc"
    force: yes
    